[workspace]
resolver = "2"
members = ["bullet-utils"]

[workspace.package]
license = "MIT"
authors = ["Jamie Whiting"]

[package]
name = "bullet"
version = "1.0.0"
edition = "2021"
license.workspace = true
authors.workspace = true

[workspace.dependencies]
bulletformat = "1.0.0"

[features]
cuda = ["bindgen", "cc"]

[dependencies]
bulletformat = { workspace = true }

[build-dependencies]
bindgen = { version = "0.68.1", optional = true }
cc = { version = "1.0.83", optional = true }

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = true
